### ISSUE TITLE
how to use it ?

### ISSUE THREAD

**Issue by zhuhe25** [devonfw/extension-pack-vscode#11]
Category: Bug or enhancement

Severity: Low , Medium, High, Critical

Expected behaviour (In case of bug)

Actual/current behaviour (In case of bug)

Steps to reproduce (In case of bug)

Description of issue / expected enhacement /Comments

Your environment - windows/Linux, Devonfw version , component

**Comment by hohwille** [comment]
like any other extension for visual studio code:
https://code.visualstudio.com/learn/get-started/extensions

If you use https://github.com/devonfw/ide/ you will get it automatically when you run vscode.

**Comment by hohwille** [comment]
The link is already included in the README of this repo:
https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack

**Comment by sjimenez77** [comment]
Hi @hohwille, I am not sure how to improve the documentation to explain how to use a set of extensions as many others any user may find in the marketplace. 

I will check anyhow to see if there is something we can explain better. 

@zhuhe25 as you can see this extension pack contains a lot of extensions for many different purposes, if you need help on a specific topic I would suggest to check documentation or visit marketplace page or repository of the extension you want to get more info.
